# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-02 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geoships_info_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 33, 27, 619937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 9, 33, 27, 613360, tzinfo=utc)),
        ),
    ]
