# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoships_info_app', '0002_auto_20191102_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
